apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: app
        image: student-management:prod
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
